Use noTrackingStrategy for SAC consumers without explicit --store-every
When -sac is used without an explicit --store-every, the consumer
previously got auto-tracking enabled silently. With this change,
explicit --store-every is required, even for SAC consumers.

This PR started by investigating the following null pointer:

```
14:04:49.984 [rabbitmq-stream-consumer-connection-19] WARN  c.r.stream.impl.StreamConsumer - Error in consumer update listener
java.lang.NullPointerException: Cannot invoke "com.rabbitmq.stream.impl.Client$QueryOffsetResponse.isOk()" because "response" is null
        at com.rabbitmq.stream.impl.OffsetTrackingUtils.storedOffset(OffsetTrackingUtils.java:53)
        at com.rabbitmq.stream.impl.StreamConsumer.storedOffset(StreamConsumer.java:552)
        at com.rabbitmq.stream.impl.StreamConsumer.storedOffset(StreamConsumer.java:566)
        at com.rabbitmq.stream.impl.StreamConsumer.getStoredOffsetSafely(StreamConsumer.java:301)
        at com.rabbitmq.stream.impl.StreamConsumer.getStoredOffset(StreamConsumer.java:285)
        at com.rabbitmq.stream.impl.StreamConsumer.lambda$new$4(StreamConsumer.java:187)
        at com.rabbitmq.stream.impl.StreamConsumer.consumerUpdate(StreamConsumer.java:415)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager.lambda$new$11(ConsumersCoordinator.java:861)
        at com.rabbitmq.stream.impl.ServerFrameHandler$ConsumerUpdateFrameHandler.doHandle(ServerFrameHandler.java:802)
        at com.rabbitmq.stream.impl.ServerFrameHandler$BaseFrameHandler.handle(ServerFrameHandler.java:289)
        at com.rabbitmq.stream.impl.Client$FrameHandlerTask.run(Client.java:3161)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.lang.Thread.run(Thread.java:1474)
```